apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "ytechnologies.org"
    http:
      paths:
      - pathType: Prefix
        path: "/v1"
        backend:
          service:
            name: web
            port:
              number: 8080
      - pathType: Prefix
        path: "/v2"
        backend:
          service:
            name: web2
            port:
              number: 80