apiVersion: v1
kind: Pod
metadata:
  name: game-app
spec:
  containers:
    - name: game-app
      image: public.ecr.aws/docker/library/busybox:1.36.0-musl
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: PLAYER_INITIAL_LIVES # Notice that the case is different here                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: game-demo           # The ConfigMap this value comes from.
              key: player_initial_lives # The key to fetch.