apiVersion: v1
kind: Pod
metadata:
  name: high-pod
spec:
  priorityClassName: high-pc
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "400m"
        memory: "200Mi"