apiVersion: v1
kind: Pod
metadata:
  name: mid-pod
spec:
  priorityClassName: mid-pc
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "500m"
        memory: "1000Mi"