apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: web
        ports:
        - containerPort: 80
      volumes:
      - name: web
        hostPath:
          path: /tmp/web
          type: DirectoryOrCreate
status: {}
