apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:               #Grantee to get
        memory: "1Gi"
        cpu: "1000m". #1 core
      limits:                 #Never go above the value
        memory: "2Gi"
        cpu: "2000Gi"  #2 Core
  - name: log-aggregator
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        memory: "250Mi" #1000 = 1GB
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"