apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
spec:
  storageClassName: "" # If not defined, it will create pv with default storage class.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi